load("C:/Users/inspiron/Desktop/RPractice/recent.RData")
usersummary2 <- cbind(usersummary,m$User.since.Days)
View(usersummary2)
usersummary2 <- cbind(usersummary,m$Gender)
usersummary2 <- cbind(usersummary2,m$User.since.Days)
usersummary <- usersummary2
library(rpart)
library(rpart.plot)
mod <- usersummary2[-c(2,9:12)]
View(mod)
mod <- unique(mod)
View(mod)
rpartmodel <- rpart(store ~ .,mod)
rpartmodel <- rpart(Store ~ .,mod)
save.image("~/rpartmodel.RData")
prp(rpartmodel)
rpartmodel <- rpart(Store ~ exitcount + txncount + totalexitcount + totaltxn + m$Gender + m$User.since.Days, mod)
colnames(mod)[9] <- "usersince"
colnames(mod)[8] <- "usergender"
rpartmodel <- rpart(Store ~ exitcount + txncount + totalexitcount + totaltxn + m$Gender + m$User.since.Days, mod)
rpartmodel <- rpart(Store ~ exitcount + txncount + totalexitcount + totaltxn + usergender + usersince, mod)
prp(rpartmodel)
mod2 <- subset(mod , Store != "Paytm")
rpartmodel <- rpart(Store ~ exitcount + txncount + totalexitcount + totaltxn + usergender + usersince, mod2)
prp(rpartmodel)
rpartmodel <- rpart(meanOVStore ~ exitcount + txncount + totalexitcount + totaltxn + usergender + usersince + Store, mod2)
prp(rpartmodel)
x <- c("Amazon", "Flipkart", "Snapdeal", "Shopclues")
h <- grepl(paste(x, collapse = "|"), mod$Store)
mod2 <- subset(mod,h == TRUE)
rpartmodel <- rpart(meanOVStore ~ exitcount + txncount + totalexitcount + totaltxn + usergender + usersince + Store, mod2)
prp(rpartmodel)
View(mod2)
rpartmodel <- rpart(Store ~ exitcount + txncount + totalexitcount + totaltxn + usergender + usersince, mod2)
prp(rpartmodel)
rpartmodel <- rpart(totaltxn ~ exitcount  + totalexitcount + txncount + usergender + usersince + Store, mod2)
prp(rpartmodel)
library(randomForest)
write.csv(usersummary,"usersummary.csv")
